### Network Tasks ###
---
- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when:
    - ansible_hostname != inventory_hostname

- name: Install needed NetworkManager libraries
  ansible.builtin.package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
    state: present

- name: Ensure NetworkManager is running
  service:
    name: NetworkManager
    state: started
    enabled: true

# - name: Rename network interfaces

- name: Set IP for internal interfaces
  block:
    - name: Internal
      community.general.nmcli:
        conn_name: internal
        ifname: eth1
        type: ethernet
        ip4: 10.0.1.1
        state: present
    - name: External
      community.general.nmcli:
        conn_name: external
        ifname: eth0
        type: ethernet
        ip4: 10.0.1.1
        state: present
    - name: wireless
      community.general.nmcli:
        conn_name: internal
        ifname: wlan0
        type: ethernet
        ip4: 10.0.1.2
        state: present

- name: Copy iptables script
  ansible.builtin.copy:
    src: files/iptables.sh
    dest: /etc/init.d/iptables.sh
    mode: 0755
    owner: root
    group: root

- name: Copy dnsmasq config
  ansible.builtin.copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: 0644
    owner: root
    group: root
# - name: Start wireless access point
