### Network Tasks ###
---
- name: Include variables
  include_vars:
    file: vars/networking.yaml
    name: networking

### Begin mitmproxy Configuration ###
# https://docs.mitmproxy.org/stable/howto-transparent/#linux
- name: Enable IPv4 Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Enable IPv6 Forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1

- name: Disable ICMP Redirects
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
### End mitmproxy Configuration ###

### Begin NetworkManager Configuration ###
- name: Install needed NetworkManager libraries
  ansible.builtin.package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
    state: present

- name: Ensure NetworkManager is running
  service:
    name: NetworkManager
    state: started
    enabled: true

# - name: Rename network interfaces

- name: Set IP for internal interfaces
  block:
    - name: External
      community.general.nmcli:
        conn_name: external
        ifname: eth0
        type: ethernet
        ip4: 10.0.1.1
        state: present
    - name: Internal
      community.general.nmcli:
        conn_name: internal
        ifname: eth1
        type: ethernet
        ip4: 10.0.1.1
        state: present
    - name: wireless
      community.general.nmcli:
        conn_name: internal
        ifname: wlan0
        type: ethernet
        ip4: 10.0.1.2
        state: present
### End NetworkManager Configuration ###

### Start iptables Configuration ###
- name: Copy iptables script
  ansible.builtin.copy:
    src: files/iptables.sh
    dest: /etc/init.d/iptables.sh
    mode: 0755
    owner: root
    group: root

- name: Reload iptables
  ansible.builtin.service:
    name: iptables
    state: reloaded
### End iptables Configuration ###

### Start dnsmasq Configuration ###
- name: Copy dnsmasq config
  template:
    src: files/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644
    owner: root
    group: root

- name: Enable dnsmasq systemd service
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: yes
    masked: no

- name: Start dnsmasq systemd service
  ansible.builtin.systemd:
    state: started
    name: dnsmasq
### End dnsmasq Configuration ###

### Start hostapd Configuration ###
- name: Create hostapd configuration
  ansible.builtin.template:
    src: files/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0644

- name: Enable hostapd systemd service
  ansible.builtin.systemd:
    name: hostapd
    enabled: yes
    masked: no

- name: Start hostapd systemd service
  ansible.builtin.systemd:
    state: started
    name: hostapd
### End hostapd Configuration ###
