### Prepare Packages ###
---
### Begin Package Management ###
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - zsh
    - neofetch
    - git
    - thefuck
    - nano
    - net-tools
    - nmcli
    - dnsmasq
    - iptables
    # - mitmproxy # Pull directly from project. Repository is out of date.
    - nmap
    - tshark
    - tcpdump
    - hostapd

- name: Remove packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    autoremove: true
  loop:
    - snapd

- name: Disable APT recommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/02norecommends
    mode: 0644
    create: true
    block: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";

- name: Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Remove snapd
  block:
    - name: Remove snap packages
      ansible.builtin.command: snap remove {{ item }}
      loop:
        - lxd
        - core18
        - core20
        - snapd
      when:
        - "'snapd' in ansible_facts.packages"
    - name: Remove files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/home/{{ username }}/.snap"
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
### End Package Management ###

### Begin Unattended Upgrades ###
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    update_cache: true

- block:
    - name: Copy 20auto-upgrades unattended-upgrades config
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        mode: 0644
        create: true
        block: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "1";
          APT::Periodic::Unattended-Upgrade "1";

    - name: Copy 50unattended-upgrades unattended-upgrades config
      ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: 0644
        create: true
        block: |
          Unattended-Upgrade::Automatic-Reboot "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id} stable";
              "${distro_id} ${distro_codename}-security";
              "${distro_id} ${distro_codename}-updates";
          };

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
### End Unattended Upgrades ###
