### Prepare User ###
---
### Begin User Shell Customization ###
- name: Set ZSH as default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  when: ansible_shell != "/bin/zsh"

- name: Clone/update oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/{{ username }}/.oh-my-zsh
    clone: yes
    update: yes

- name: Copy zshrc
  template:
    src: files/zshrc.j2
    dest: /home/{{ username }}/.zshrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  when:
    - "'zsh' in ansible_facts.packages"
### End User Shell Customization ###
